#!/usr/bin/env bash
# deploy-joanne.sh — deploy or update LibreJoanne on this server.
#
#   ~/scripts/deploy-joanne.sh                 # deploy the default ref
#   ~/scripts/deploy-joanne.sh main            # deploy a branch, tag or commit
#   ~/scripts/deploy-joanne.sh --status        # show what is currently deployed
#
# Layout, and why it is this way:
#
#   ~/apps/joanne              the checkout, OUTSIDE the web root
#   ~/htdocs/1qaz.ca/joanne -> ~/apps/joanne/web/app   symlink, the only public part
#
# This server runs nginx, so the .htaccess that ships in web/data does nothing. If the
# checkout sat inside the web root, web/data/librejoanne.db and web/data/config.php
# would both be downloadable over HTTP. Keeping the checkout outside and publishing
# only web/app means the database, the configuration and the caches have no URL at all.
#
# web/data is git-ignored, so config.php, the database and the caches survive updates.
set -euo pipefail

REPO_URL="${JOANNE_REPO:-https://github.com/ergosteur/joanne-eink-calendar.git}"
APP_DIR="${JOANNE_APP_DIR:-$HOME/apps/joanne}"
LINK_PATH="${JOANNE_LINK:-$HOME/htdocs/1qaz.ca/joanne}"
HEALTH_URL="${JOANNE_HEALTH_URL:-https://1qaz.ca/joanne/}"
FALLBACK_REF="${JOANNE_REF:-main}"
REF_FILE="$APP_DIR/.deployed-ref"

# Running with no argument redeploys whatever is already live, rather than silently
# moving the deployment to a different branch. Only a first install falls back.
if [ -f "$REF_FILE" ]; then
    DEFAULT_REF="$(cat "$REF_FILE")"
else
    DEFAULT_REF="$FALLBACK_REF"
fi

say()  { printf '\033[1m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[33m warn:\033[0m %s\n' "$1"; }
die()  { printf '\033[31m error:\033[0m %s\n' "$1" >&2; exit 1; }

# ------------------------------------------------------------------ status

if [ "${1:-}" = "--status" ]; then
    if [ ! -d "$APP_DIR/.git" ]; then
        echo "Not deployed: $APP_DIR does not exist."
        exit 0
    fi
    cd "$APP_DIR"
    echo "checkout : $APP_DIR"
    echo "tracking : $(cat "$APP_DIR/.deployed-ref" 2>/dev/null || echo unknown)"
    echo "ref      : $(git describe --all --always 2>/dev/null)"
    echo "commit   : $(git log -1 --format='%h %s')"
    echo "dated    : $(git log -1 --format='%ci')"
    echo "link     : $LINK_PATH -> $(readlink -f "$LINK_PATH" 2>/dev/null || echo MISSING)"
    echo "config   : $([ -f "$APP_DIR/web/data/config.php" ] && echo present || echo MISSING)"
    echo "database : $([ -f "$APP_DIR/web/data/librejoanne.db" ] && du -h "$APP_DIR/web/data/librejoanne.db" | cut -f1 || echo 'not created yet')"
    echo "health   : $(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 "$HEALTH_URL" 2>&1)"
    exit 0
fi

REF="${1:-$DEFAULT_REF}"

command -v git >/dev/null || die "git is not installed"
command -v php >/dev/null || die "php is not installed"

# ------------------------------------------------------------------ checkout

if [ ! -d "$APP_DIR/.git" ]; then
    say "Cloning $REPO_URL into $APP_DIR"
    mkdir -p "$(dirname "$APP_DIR")"
    git clone --quiet "$REPO_URL" "$APP_DIR"
fi

cd "$APP_DIR"

say "Fetching"
git remote set-url origin "$REPO_URL"
git fetch --quiet --all --prune --tags

# Resolve the ref: prefer the remote branch, fall back to a tag or raw commit.
if git rev-parse --verify --quiet "origin/$REF^{commit}" >/dev/null; then
    TARGET="origin/$REF"
elif git rev-parse --verify --quiet "$REF^{commit}" >/dev/null; then
    TARGET="$REF"
else
    die "ref '$REF' not found on origin"
fi

PREVIOUS="$(git rev-parse --short HEAD 2>/dev/null || echo none)"

say "Checking out $REF ($(git rev-parse --short "$TARGET"))"
# Deliberately no 'git clean -x': web/data holds the config, database and caches,
# and they must survive every deploy.
git checkout --quiet --detach "$TARGET"
git reset --quiet --hard "$TARGET"
printf '%s\n' "$REF" > "$REF_FILE"

# ------------------------------------------------------------------ data dir

DATA_DIR="$APP_DIR/web/data"
mkdir -p "$DATA_DIR/cache"
# PHP-FPM runs as a different user in the same group as the SSH account, so the data
# directory has to be group-writable for SQLite and the caches. setgid keeps the group
# on everything PHP creates, so both accounts can maintain the files afterwards.
chmod 2770 "$DATA_DIR" "$DATA_DIR/cache"

CONFIG="$DATA_DIR/config.php"
NEW_SETUP_PASSWORD=""
if [ ! -f "$CONFIG" ]; then
    say "Generating $CONFIG with fresh secrets"
    ENC_KEY="$(php -r 'echo bin2hex(random_bytes(32));')"
    NEW_SETUP_PASSWORD="$(php -r 'echo bin2hex(random_bytes(12));')"
    cat > "$CONFIG" <<PHPCONF
<?php
// Generated by deploy-joanne.sh. Not in version control.
//
// Room, RSS and UI defaults are inherited from config.sample.php so that upstream
// changes carry through; only the secrets and any local overrides live here.
//
// WARNING: changing encryption_key makes every stored calendar URL undecryptable.

\$config = require __DIR__ . '/config.sample.php';

\$config['security']['encryption_key'] = '${ENC_KEY}';
\$config['security']['setup_password'] = '${NEW_SETUP_PASSWORD}';
\$config['security']['db_path']        = __DIR__ . '/librejoanne.db';

return \$config;
PHPCONF
else
    say "Keeping existing $CONFIG"
fi

# Applied on every deploy, not only on creation: PHP-FPM runs as the sibling account
# in this group and must be able to read the config.
chmod 640 "$CONFIG"

# 660, not 600: PHP-FPM owns or writes this file as the other account in the group.
if [ -f "$DATA_DIR/librejoanne.db" ]; then
    chmod 660 "$DATA_DIR/librejoanne.db" 2>/dev/null || true
fi

# ------------------------------------------------------------------ publish

say "Publishing $LINK_PATH -> $APP_DIR/web/app"
mkdir -p "$(dirname "$LINK_PATH")"
if [ -e "$LINK_PATH" ] && [ ! -L "$LINK_PATH" ]; then
    die "$LINK_PATH exists and is not a symlink; refusing to replace it"
fi
ln -sfn "$APP_DIR/web/app" "$LINK_PATH"

# ------------------------------------------------------------------ verify

say "Verifying"
FAILED=0

for f in $(find "$APP_DIR/web" -name '*.php'); do
    php -l "$f" >/dev/null 2>&1 || { warn "syntax error in $f"; FAILED=1; }
done

code="$(curl -sS -o /tmp/joanne-health.$$ -w '%{http_code}' --max-time 30 "$HEALTH_URL" 2>/dev/null || echo 000)"
if [ "$code" = "200" ]; then
    if grep -qE '(Fatal error|Parse error|Warning|Deprecated|Notice):' /tmp/joanne-health.$$; then
        warn "page returned 200 but contains a PHP diagnostic:"
        grep -oE '(Fatal error|Parse error|Warning|Deprecated|Notice):.{0,90}' /tmp/joanne-health.$$ | head -3
        FAILED=1
    else
        echo "  app responds 200 and is clean"
    fi
else
    warn "app returned HTTP $code at $HEALTH_URL"
    FAILED=1
fi
rm -f /tmp/joanne-health.$$

# A JSON endpoint exercises config loading, the database and the cache directory,
# which a static page load does not.
jcode="$(curl -sS -o /tmp/joanne-cal.$$ -w '%{http_code}' --max-time 60 "${HEALTH_URL%/}/calendar.php?room=default" 2>/dev/null || echo 000)"
if [ "$jcode" = "200" ] && php -r 'exit(json_decode(file_get_contents($argv[1])) === null ? 1 : 0);' /tmp/joanne-cal.$$ 2>/dev/null; then
    echo "  calendar.php returns valid JSON"
else
    warn "calendar.php returned HTTP $jcode or invalid JSON"
    FAILED=1
fi
rm -f /tmp/joanne-cal.$$

# The whole point of the layout: confirm private files really have no URL.
# --path-as-is stops curl collapsing ../ before the request is sent, and redirects are
# deliberately not followed, because this host 302s unknown paths to its home page.
base="${HEALTH_URL%/}"
EXPOSED=0
for probe in "web/data/config.php" "web/data/librejoanne.db" "data/config.php" \
             "data/librejoanne.db" "data/config.sample.php" "../data/config.php" \
             "data/cache/" "README.md" "web/lib/db.php"; do
    pcode="$(curl -sS --path-as-is -o /dev/null -w '%{http_code}' --max-time 15 "$base/$probe" 2>/dev/null || echo 000)"
    if [ "$pcode" = "200" ]; then
        warn "EXPOSED: $base/$probe returned 200"
        EXPOSED=1
        FAILED=1
    fi
done
[ "$EXPOSED" -eq 0 ] && echo "  private paths are not reachable over HTTP"

# ------------------------------------------------------------------ summary

echo
say "Deployed"
echo "  ref        : $REF ($(git rev-parse --short HEAD))"
echo "  previous   : $PREVIOUS"
echo "  commit     : $(git log -1 --format='%s')"
echo "  url        : $HEALTH_URL"
echo "  dashboard  : ${base}/manage.php"
if [ -n "$NEW_SETUP_PASSWORD" ]; then
    echo
    echo "  FIRST RUN — setup password (shown once, also in $CONFIG):"
    echo "      $NEW_SETUP_PASSWORD"
    echo "  Use it at ${base}/manage.php to create the admin account, then it is spent."
fi

[ "$FAILED" -eq 0 ] || { echo; die "deployed, but verification reported problems (see warnings above)"; }
